api_platform:
    title: Electronica Don Pepe API
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    patch_formats:
        jsonapi: ['application/vnd.api+json']   
    use_symfony_listeners: true